### ISSUE TITLE
Feature: Support custom Apache time format

### ISSUE THREAD

**Issue by TrafeX** [wvanbergen/request-log-analyzer#138]
Hi,

It would be nice if this worked:
`request-log-analyzer --apache-format "[%{%Y-%m-%dT%T%z}t] \"%r\" %>s %b"`

It's allowed to specify your own time format in the Apache log (see here: http://httpd.apache.org/docs/2.2/mod/mod_log_config.html#formats) and when you've done that, there's no way to use this awsome tool exept creating your own file format definition.

**Comment by barttenbrinke** [comment]
We'll accept pull requests for this :)

**Comment by wvanbergen** [comment]
This actually **is** supported (using the `--apache-format` command line option). [1]

However, we may not support all log directives Apache supports, and escaping it on the command line may cause issues. If the format is not exactly right, you will get 0 results instead of an error messages.

PRs to improve any of these are welcome.

[1] https://github.com/wvanbergen/request-log-analyzer/blob/f05de5e7df772f56c76b3322efb702865289eda3/lib/request_log_analyzer/file_format/apache.rb#L15
