### ISSUE TITLE
sample output wiki page is empty

### ISSUE THREAD

**Issue by ssbarnea** [wvanbergen/request-log-analyzer#167]
https://github.com/wvanbergen/request-log-analyzer/wiki/sample-output is empty :(

**Comment by chmac** [comment]
Yes, it is, I was about to post the same issue. :(

**Comment by wvanbergen** [comment]
I think the page went missing when the wiki was converted at some point. I re-added some sample output based on one of the Rails fixture files in the repository. It's not a great example output because the log file is very limited, but I don't have a better file available. Anybody able to contribute one, maybe after redacting some of the output?
