### ISSUE TITLE
Hodel 3000 and Oink

### ISSUE THREAD

**Issue by itsderek23** [wvanbergen/request-log-analyzer#54]
Hi guys,

I'd love to get memory metrics added to the RLA output. One way to do this is using the Oink Rails plugin along with the Hodel3000Logger format:

http://github.com/noahd1/oink
http://github.com/topfunky/hodel_3000_compliant_logger/tree/master

The hodel3000 format adds the request PID to the log file. Sample w/Oink output:

```
Jun 08 11:29:19 local rails[25233]: Memory usage: 754816 | PID: 25233
Jun 08 11:29:19 local rails[25233]: Completed in 189ms (View: 0, DB: 293) | 200 OK [http://localhost/file_records/inline/5171]
```

The PID is needed as most Rails applications have multiple processes serving the application, so judging the memory change requires a PID for comparison.

You can see how Oink parses a Rails log file here:

http://github.com/noahd1/oink/blob/master/lib/oink/memory_usage_reporter.rb

I'd like to add Oink output, but I wanted to see if you had any thoughts on direction before I dig in. I'm not sure it's possible without a decent chunk of RLA refactoring. 

The piece I'm struggling with: where/how to report the change in memory usage when a request is completed.

From the earlier sample, you can see that the process memory usage is logged immediately before the :completed line of a request. 

Creating a line definition for the memory line looks straight forward. I'd need to capture the PID and Memory usage. 

When the footer line of the request is encountered, I'd like to store the change in memory usage with the request data. To do that, I'd need to read the previously recorded memory usage of the process. 

Do you have suggestions on getting started?

**Comment by wvanbergen** [comment]
I have played around with Oink as well. It revealed some glared memory problems on one of the most visited pages of the website I was analyzing. Very useful tool!

What you will need to do is to store the previous request to compute the memory differences. Because of multiple processes, you will need to store the PID as well. It is probably best to add a hash instance variable to the file format, called previous_request_per_pid or something, which maps a PID to the previous request. When a request is returned from the parser, it should be stored in this hash. The next request can then inspect this hash to calculate the memory difference.

The Request#validate method is called just before the request is returned, which is a suitable place to store it in the hash.

```
class OinkFormat < RequestLogAnalyzer::FileFormat::Base

  attr_accessor :previous_requests

  # put your stuff here

  # override the default Request class for this file format
  class Request < RequestLogAnalyzer::Request
    def validate
       # get the previous request for this PID
       file_format.previous_requests[self[:pid]]
    end
  end
end
```

**Comment by wvanbergen** [comment]
I pressed the "comment & close" button by accident, sorry!
Also, the code example is not tested at all, so don't get mad if this doesn't work. :-)

**Comment by barttenbrinke** [comment]
Oink looks nice enough to support anyway :). You can probably inherit from our default rails logger and add the oink functionality to that.

**Comment by itsderek23** [comment]
Thanks guys! I'll run with this and see what I can put together.
