### ISSUE TITLE
Support Tomcat processing time log in milli seconds

### ISSUE THREAD

**Issue by romk** [wvanbergen/request-log-analyzer#89]
Tomcat's AccessLogValve reports processing time in milli seconds, this results in slightly optimistic reports...

**Comment by wvanbergen** [comment]
Can you provide a sample snippet of a Tomcat log?

**Comment by romk** [comment]
66.11.130.230 - - [27/Jan/2011:00:25:00 -0500] "GET /asyws/rest/customers/1000000099/carts/10000002227301 HTTP/1.1" 200 3034 "-" "Zend_Http_Client" 40
66.11.130.230 - - [27/Jan/2011:00:25:00 -0500] "GET /asyws/rest/customers/1000000099/carts/10000002227301 HTTP/1.1" 200 3034 "-" "Zend_Http_Client" 44
66.11.130.230 - - [27/Jan/2011:00:25:00 -0500] "GET /asyws/rest/customers/1000000099/temporary_orders/10000002290349 HTTP/1.1" 200 3801 "-" "Zend_Http_Client" 27
66.11.130.230 - - [27/Jan/2011:00:25:00 -0500] "GET /asyws/rest/customers/1000000099/addresses HTTP/1.1" 200 718 "-" "Zend_Http_Client" 16
6

this was created with the following config:
        <Valve  className="org.apache.catalina.valves.AccessLogValve"
                 directory="${HYBRIS_LOG_DIR}/tomcat"
                   prefix="access."
                   suffix=".log"
                   pattern="%h %l %u %t &quot;%r&quot; %s %b &quot;%{Referer}i&quot; &quot;%{User-Agent}i&quot; %D"
          />

**Comment by wvanbergen** [comment]
This looks like a format compatible with Apache access log files. You can supply the format string to the command line using the --apache-format parameter. However, in Apache, the %D directive logs the request duration in microseconds instead of milliseconds, so the log format is not fully compatible.

If there is no way to differentiate between an Apache access log an a Tomcat access log, the only way to overcome this is to supply a Tomcat file format and use the --format parameter to tell request-log-analyzer what file format you are using instead of relying on the auto-detection feature.

**Comment by romk** [comment]
Agree.

Simple workaround I just tried is to specify '%D000' in the pattern.

**Comment by wvanbergen** [comment]
Good idea! I immediately implemented it, but you have to use the following format syntax: "%{milli}D" because this corresponds better with the other format string syntax.

It is available now on master.
